/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ConfigConfigIdUploadRouteImport } from './pages/config/$configId/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigConfigIdUploadRoute = ConfigConfigIdUploadRouteImport.update({
  id: '/config/$configId/upload',
  path: '/config/$configId/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config/$configId/upload': typeof ConfigConfigIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config/$configId/upload': typeof ConfigConfigIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config/$configId/upload': typeof ConfigConfigIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/config/$configId/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config/$configId/upload'
  id: '__root__' | '/' | '/config/$configId/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigConfigIdUploadRoute: typeof ConfigConfigIdUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$configId/upload': {
      id: '/config/$configId/upload'
      path: '/config/$configId/upload'
      fullPath: '/config/$configId/upload'
      preLoaderRoute: typeof ConfigConfigIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigConfigIdUploadRoute: ConfigConfigIdUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
